; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "Cross Cleaner"
#define MyAppVersion "2.0.2.8.2"
#define MyAppPublisher "Neki_play"
#define MyAppURL "https://github.com/Cross-Cleaner/Cross-Cleaner"
#define MyAppExeName "desktop.exe"
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

; Architecture the binaries in target\release were built for. The release
; workflow compiles this script twice, once per runner, so pass the architecture
; on the command line: iscc /DMyArch=arm64 build_setup.iss
; Default is x64, which is what a local build produces on a normal machine.
#ifndef MyArch
  #define MyArch "x64"
#endif

; The output name carries the architecture so both installers can live in the
; same release, and so winget (which matches ^Cross_Cleaner_Setup(_Arm64)?\.exe$)
; can label each installer in the manifest instead of guessing from one file.
#if MyArch == "arm64"
  #define MyOutputBaseFilename "Cross_Cleaner_Setup_Arm64"
  ; "arm64" refuses the installer on anything but a native arm64 CPU, so the
  ; x64 setup is the only one installable through emulation.
  #define MyArchitecturesAllowed "arm64"
#else
  #define MyOutputBaseFilename "Cross_Cleaner_Setup"
  ; "x64compatible" includes x64 and Windows 11 on Arm, which runs x64 binaries.
  #define MyArchitecturesAllowed "x64compatible"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
; One AppId for both architectures on purpose: the arm64 setup is an in-place
; replacement for the same app, so Windows treats it as an upgrade of an existing
; install instead of leaving two copies of the app behind.
AppId={{63C69122-AC80-4866-B328-5C3188A01F76}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; Compiled from the {#MyArch} build of desktop.exe, so only that CPU can run it.
ArchitecturesAllowed={#MyArchitecturesAllowed}
; "ArchitecturesInstallIn64BitMode" requests that the install be done in "64-bit mode"
; on those systems, meaning the native Program Files directory and 64-bit registry view.
ArchitecturesInstallIn64BitMode={#MyArchitecturesAllowed}
; SetupArchitecture is an Inno Setup 7 directive and the runner image ships 6.x,
; where it stays commented out. It does not matter for the architecture split:
; the default 32-bit setup stub runs on x64 and arm64 Windows alike, and the
; restriction is carried by ArchitecturesAllowed above.
;SetupArchitecture=x64
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=innosetup\compiler
OutputBaseFilename={#MyOutputBaseFilename}
; The icon lives with the crate that owns it (see crates/winicon), which both
; binaries are stamped from, so the installer shows the same one.
SetupIconFile=crates\winicon\assets\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "target\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

;[Run]
; Verb: runas запрашивает права администратора (UAC) перед запуском exe (требуется Inno Setup 6.3+)
;Filename: "{app}\{#MyAppExeName}"; Verb: runas; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent shellexec

