use rodio::mixer::Mixer;
use rodio::stream::play;
use rodio::{DeviceSinkBuilder, MixerDeviceSink};
use std::io::{Cursor, Read};
use std::sync::{LazyLock, OnceLock};

use flate2::read::GzDecoder;

use crate::config;

/// Compressed (gz) UI sounds, generated by `gui/build.rs` into `OUT_DIR`
/// to keep the binary small (same approach as `database/build.rs`).
static CHECK_BYTES: LazyLock<Vec<u8>> =
    LazyLock::new(|| gunzip(include_bytes!(concat!(env!("OUT_DIR"), "/check.mp3.gz"))));
static UNCHECK_BYTES: LazyLock<Vec<u8>> =
    LazyLock::new(|| gunzip(include_bytes!(concat!(env!("OUT_DIR"), "/unckeck.mp3.gz"))));
static DONE_BYTES: LazyLock<Vec<u8>> =
    LazyLock::new(|| gunzip(include_bytes!(concat!(env!("OUT_DIR"), "/done.mp3.gz"))));
static CLICK_BYTES: LazyLock<Vec<u8>> =
    LazyLock::new(|| gunzip(include_bytes!(concat!(env!("OUT_DIR"), "/click.mp3.gz"))));
static POP_BYTES: LazyLock<Vec<u8>> =
    LazyLock::new(|| gunzip(include_bytes!(concat!(env!("OUT_DIR"), "/pop.mp3.gz"))));

/// Decompresses a gz-compressed sound produced at build time.
fn gunzip(data: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    GzDecoder::new(data)
        .read_to_end(&mut out)
        .expect("Failed to decompress sound");
    out
}

/// Convenience wrapper around rodio for playing short embedded UI sounds.
/// Keeps the output device sink alive; each sound is decoded and played on a
/// detached player so it never blocks the UI thread.
pub struct Sounds {
    _sink: MixerDeviceSink,
    mixer: Mixer,
}

impl Sounds {
    /// Opens the default output device. Returns `None` when audio is not
    /// available (no device, headless CI, etc.) so the app keeps working
    /// silently.
    pub fn new() -> Option<Self> {
        let sink = DeviceSinkBuilder::open_default_sink().ok()?;
        let mixer = sink.mixer().clone();
        Some(Self { _sink: sink, mixer })
    }

    /// Decodes and plays embedded MP3 bytes; errors are ignored by design.
    fn play(&self, bytes: &'static [u8], volume: f32) {
        if let Ok(player) = play(&self.mixer, Cursor::new(bytes)) {
            player.set_volume(volume);
            player.detach();
        }
    }
}

static SOUNDS: OnceLock<Sounds> = OnceLock::new();

/// Initializes the audio device once. Safe to call multiple times; failures
/// (no audio device, headless CI) leave the app working silently.
pub fn init() {
    if let Some(s) = Sounds::new() {
        let _ = SOUNDS.set(s);
    }
}

fn get() -> Option<&'static Sounds> {
    SOUNDS.get()
}

/// Button click.
pub fn click() {
    if let Some(s) = get() {
        s.play(&CLICK_BYTES, config::get().click_volume);
    }
}

/// Checkbox became checked.
pub fn check() {
    if let Some(s) = get() {
        s.play(&CHECK_BYTES, config::get().check_volume);
    }
}

/// Checkbox became unchecked.
pub fn uncheck() {
    if let Some(s) = get() {
        s.play(&UNCHECK_BYTES, config::get().check_volume);
    }
}

/// Cleaning finished.
pub fn done() {
    if let Some(s) = get() {
        s.play(&DONE_BYTES, config::get().done_volume);
    }
}

pub fn pop() {
    if let Some(s) = get() {
        s.play(&POP_BYTES, config::get().sound_volume);
    }
}
