//! UI sounds, shared by both frontends.
//!
//! The same five sounds play for the same events in `gui` and `tui`: a click on
//! an action, a check, an uncheck, opening a popup, and finishing a cleaning run.
//! Keeping the player here means both frontends agree on the file names and the
//! volume semantics from [`crate::config`] instead of each carrying its own
//! copy.
//!
//! Playback is best effort throughout: a machine with no audio device (a headless
//! build server, a container, a CI runner) leaves the app working silently.

#[cfg(not(target_os = "android"))]
use rodio::mixer::Mixer;
#[cfg(not(target_os = "android"))]
use rodio::stream::play;
#[cfg(not(target_os = "android"))]
use rodio::{DeviceSinkBuilder, MixerDeviceSink};
use std::io::{Cursor, Read};
#[cfg(not(target_os = "android"))]
use std::sync::OnceLock;

use flate2::read::GzDecoder;

use crate::config;

/// Compressed (gz) UI sounds, generated by this crate's build script into
/// `OUT_DIR`. Decompressed on demand per playback, so no `Vec<u8>` stays resident
/// in RAM while idle.
static CHECK_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/check.mp3.gz"));
static UNCHECK_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/unckeck.mp3.gz"));
static DONE_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/done.mp3.gz"));
static CLICK_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/click.mp3.gz"));
static POP_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/pop.mp3.gz"));

/// Decompresses a gz-compressed sound produced at build time.
fn gunzip(data: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    GzDecoder::new(data)
        .read_to_end(&mut out)
        .expect("Failed to decompress sound");
    out
}

/// Convenience wrapper around rodio for playing short embedded UI sounds.
/// Keeps the output device sink alive; each sound is decoded and played on a
/// detached player so it never blocks the UI thread.
#[cfg(not(target_os = "android"))]
pub struct Sounds {
    _sink: MixerDeviceSink,
    mixer: Mixer,
}

#[cfg(not(target_os = "android"))]
impl Sounds {
    /// Opens the default output device. Returns `None` when audio is not
    /// available (no device, headless CI, etc.) so the app keeps working
    /// silently.
    pub fn new() -> Option<Self> {
        let sink = DeviceSinkBuilder::open_default_sink().ok()?;
        let mixer = sink.mixer().clone();
        Some(Self { _sink: sink, mixer })
    }

    /// Decompresses then decodes and plays MP3 bytes; the `Vec` is moved into the
    /// player and freed after playback.
    fn play_gz(&self, gz_bytes: &'static [u8], volume: f32) {
        let decoded = gunzip(gz_bytes);
        if let Ok(player) = play(&self.mixer, Cursor::new(decoded)) {
            player.set_volume(volume);
            player.detach();
        }
    }
}

#[cfg(not(target_os = "android"))]
static SOUNDS: OnceLock<Sounds> = OnceLock::new();

/// Initializes the audio device once. Safe to call multiple times; failures
/// (no audio device, headless CI) leave the app working silently.
#[cfg(not(target_os = "android"))]
pub fn init() {
    if let Some(s) = Sounds::new() {
        let _ = SOUNDS.set(s);
    }
}
#[cfg(target_os = "android")]
pub fn init() {}

#[cfg(not(target_os = "android"))]
fn get() -> Option<&'static Sounds> {
    SOUNDS.get()
}

/// Button click.
pub fn click() {
    #[cfg(not(target_os = "android"))]
    if let Some(s) = get() {
        s.play_gz(CLICK_GZ, config::get().click_volume);
    }
}

/// Checkbox became checked.
pub fn check() {
    #[cfg(not(target_os = "android"))]
    if let Some(s) = get() {
        s.play_gz(CHECK_GZ, config::get().check_volume);
    }
}

/// Checkbox became unchecked.
pub fn uncheck() {
    #[cfg(not(target_os = "android"))]
    if let Some(s) = get() {
        s.play_gz(UNCHECK_GZ, config::get().check_volume);
    }
}

/// Cleaning finished.
pub fn done() {
    #[cfg(not(target_os = "android"))]
    if let Some(s) = get() {
        s.play_gz(DONE_GZ, config::get().done_volume);
    }
}

/// A popup or menu was opened.
pub fn pop() {
    #[cfg(not(target_os = "android"))]
    if let Some(s) = get() {
        s.play_gz(POP_GZ, config::get().sound_volume);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every embedded sound must be real gzip data: a build-script glitch that
    /// produced an empty or uncompressed file would otherwise only show up as a
    /// silent playback failure at runtime.
    #[test]
    fn every_embedded_sound_decompresses() {
        let sounds: [(&str, &[u8]); 5] = [
            ("check", CHECK_GZ),
            ("uncheck", UNCHECK_GZ),
            ("done", DONE_GZ),
            ("click", CLICK_GZ),
            ("pop", POP_GZ),
        ];
        for (name, gz) in sounds {
            let raw = gunzip(gz);
            assert!(!raw.is_empty(), "{name} decompressed to nothing");
            assert!(
                raw.starts_with(b"ID3") || raw.len() > 1024,
                "{name} does not look like an MP3",
            );
        }
    }

    /// Gzip magic, checked on the embedded bytes directly.
    #[test]
    fn every_embedded_sound_is_gzipped() {
        for gz in [CHECK_GZ, UNCHECK_GZ, DONE_GZ, CLICK_GZ, POP_GZ] {
            assert_eq!(&gz[..2], &[0x1f, 0x8b], "not a gzip stream");
        }
    }

    /// The player is a no-op without a device, and `init` must survive that.
    #[test]
    fn init_and_play_are_safe_without_an_audio_device() {
        init();
        // None of these may panic even when `SOUNDS` was never populated.
        click();
        check();
        uncheck();
        pop();
        done();
    }
}