[package]
name = "database"
version = "1.0.0"
edition = "2024"

[dependencies]
tabled = "0.18.0"
whoami = "1.5.2"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
disk-name = "1.0.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"