[package]
name = "cleaner"
version = "0.2.0"
edition = "2024"

[dependencies]
glob = "0.3.2"
database = { path = "../database" }

[profile.release] # optimize file size
lto = true
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
debug = false
